### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'colors')

### ISSUE THREAD

**Issue by xtareq** [xtareq/iqraui#4]
Button.tsx:50 Uncaught TypeError: Cannot read properties of undefined (reading 'colors')
    at Button.tsx:50:107
    at Ne (flatten.js:68:22)
    at e2.generateAndInjectStyles (ComponentStyle.js:91:29)
    at StyledComponent.js:87:22
    at StyledComponent.js:96:10
    at O2 (StyledComponent.js:174:44)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateForwardRef (react-dom.development.js:19226:20)
    at beginWork (react-dom.development.js:21636:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)

**Comment by xtareq** [comment]
Must be wrap with Iqra Provider
```jsx 
      <IqraProvider>
        <Button color='primary'>Hello</Button>
      </IqraProvider>
`
